metrics/Cargo.toml
metrics/src/metrics/mod.rs

dashmap offers better performance in benchmarks than the chashmap
does, particularly for heavily contended accesses.
Changes the internal storage of the metrics crate to use dashmap
instead, providing about a 2x speedup under heavy contention.

metrics: switch to dashmap

---

ratelimiter/examples/bursty.rs
ratelimiter/src/lib.rs

Adds a function to return the current rate and renames the
functions to set both rate and strategy.

ratelimiter: add function to return current rate

---

Cargo.toml
datastructures/src/histogram/mod.rs
histogram/.gitignore
histogram/CHANGELOG.md
histogram/Cargo.toml
histogram/README.md
histogram/src/bucket/mod.rs
histogram/src/counter/mod.rs
histogram/src/error/mod.rs
histogram/src/histograms/mod.rs
histogram/src/indexing/mod.rs
histogram/src/indexing/u16.rs
histogram/src/indexing/u32.rs
histogram/src/indexing/u64.rs
histogram/src/indexing/u8.rs
histogram/src/lib.rs

Problem
Current histogram implementation in datastructures crate is focused on
histograms for u64 values. We can expand upon this to provide
histograms which operate on other values and can be either atomic or
non-atomic.
Solution
Adds a dedicated histogram crate with atomic and non-atomic
implementations for u8, u16, u32, and u64 values.

add dedicated histogram crate

---

Cargo.toml
streamstats/Cargo.toml
streamstats/src/lib.rs

Problem
Histograms can be space inefficient for calculating percentiles
across a set of measurements when minimal lookback is required.
The current implementation in `datastructures` keeps a buffer of
values seen so they can be removed later in addition to the actual
histogram bucket storage.
For u64 values and counters, this is ~50kB of bucket storage plus
16B (timestamp) + 8B (value) + 8B (count) + 8B (direction) => 40B
per value in history.
Alternatively, we can maintain a ring buffer of values, and a sorted
buffer for calculating percentiles. For u64 values, this is 16B per
value. We could even include a timestamp and stay at 32B per value
in history, keeping the footprint much less than the histogram
approach.
Solution
Adds a new crate that allows calculating a percentile from a ring …

add streamstats for percentiles across a stream of measurements

---

Cargo.toml
heatmap/src/lib.rs
histogram/src/indexing/mod.rs
histogram/src/indexing/u16.rs
metrics2/Cargo.toml
metrics2/src/lib.rs
streamstats/Cargo.toml
streamstats/src/lib.rs

Adds a work-in-progress metrics library which will eventually be
used to replace the existing metrics library. Makes better use of
generic types to allow specifying the precision of both recorded
values and internal counters. Additionally, allows for using more
efficient datastructures for summarization.

metrics2: adds a WIP metrics library

---

metrics/src/channel/mod.rs
metrics/src/lib.rs
metrics/src/metrics/mod.rs

Problem
For some use-cases, we might not know the parameters for a summary
until runtime. For example, an application with a dynamic sampling rate
that still needs to use a streaming summary for percentiles might not
know the number of samples to retain for percentile calculation until
runtime. This can make statistic types harder to implement in order to
allow dynamic summary configurations.
Solution
Add a method to set the summary type for an already registered statistic
Result
Easier to implement dynamic configuration of summary types

metrics: add method to add summary to registered statistic

---

metrics/src/channel/mod.rs
metrics/src/lib.rs

Counter updates were missing a write to the refreshed time. This
would cause incorrect summary stats to be generated.

metrics: bugfix for counter summary stats

---

metrics/src/channel/mod.rs
metrics/src/metrics/mod.rs
streamstats/src/lib.rs

Currently, we have `set_summary` function, which will update the
summary structure for the channel unconditionally. For some
use-cases, we might want to conditionally add a summary struct to
the existing channel. This may be used for dynamically registered
metric sources.

metrics: add function to add a summary if one doesn't exist

---

metrics/src/channel/mod.rs
metrics/src/lib.rs
metrics/src/metrics/mod.rs
metrics/src/traits/value.rs

Adds methods to allow incrementing a counter. This is useful when
the counter represents an aggregate of individual observations,
such as when there is no underlying counter being sampled.

metrics: add counter increment

---

heatmap/src/atomic.rs
heatmap/src/lib.rs
heatmap/src/slice.rs
heatmap/src/standard.rs
histogram/src/histograms/atomic.rs
histogram/src/histograms/standard.rs
histogram/src/lib.rs
waterfall/Cargo.toml
waterfall/examples/simulator.rs
waterfall/src/lib.rs

Refactoring waterfall to use standalone heatmap crate so it is now
compatible with heatmaps based on std::time::Instant

waterfall: refactor to use standalone heatmap crate

---

waterfall/src/lib.rs

Reduces the memory utilization of the temporary histogram
by reducing the precision. This prevents excessive memory
usage with large u64 values.

waterfall: reduce precision of temporary histogram

---

heatmap/src/error/mod.rs
heatmap/src/heatmaps/atomic.rs
heatmap/src/heatmaps/mod.rs
heatmap/src/heatmaps/standard.rs
heatmap/src/lib.rs
heatmap/src/window/mod.rs
histogram/src/bucket/mod.rs
histogram/src/counter/mod.rs
histogram/src/error/mod.rs
histogram/src/histograms/atomic.rs
histogram/src/histograms/standard.rs
histogram/src/indexing/mod.rs
histogram/src/indexing/u32.rs
histogram/src/indexing/u64.rs
histogram/src/indexing/u8.rs
waterfall/src/lib.rs

Improve the error types and documentation for histograms and
heatmaps.
Adds a new `HeatmapError` type.

improve error types and documentation for histograms and heatmaps

---

waterfall/src/lib.rs

Possible to have text overflow beyond the buffer, this change adds
checking before attempting to set the pixel value to make sure it
is within the image bounds.

waterfall: add bounds checking to text rendering

---

logger/src/lib.rs

Removes the log level message on logger initialization.

logger: remove log level message on initialization

---

waterfall/examples/simulator.rs
waterfall/src/lib.rs

Adds smoothing option to the waterfall which works by applying an
image blur before colorizing the image buffer. This may be useful
for some data distributions to help reduce artifacting across
bucket width changes at the cost of reducing the effective detail
within the waterfall and potential to introduce other artifacts.
Adds smoothed versions to the simulator to help illustrate the
differences.

waterfall: add smoothing

---

histogram/Cargo.toml
histogram/benches/standard.rs
histogram/src/indexing/u16.rs
histogram/src/indexing/u32.rs
histogram/src/indexing/u64.rs
histogram/src/indexing/u8.rs

Improves the indexing performance of the histogram implementations
by removing the `log10()`. Results in ~60% reduction in time to
increment large values.

histogram: improve indexing performance

---

histogram/benches/standard.rs
histogram/src/histograms/standard.rs

Adds a fast-path for `sub_assign()` which is used heavily in the
heatmap crate. This fast path reduces the runtime of the operation
from ~200ms to < 10ms for the case added in the benchmark.

histogram: improve performance of `sub_assign()`

---

histogram/Cargo.toml
histogram/benches/atomic.rs
histogram/benches/standard.rs
histogram/src/histograms/atomic.rs
histogram/src/indexing/u16.rs
histogram/src/indexing/u32.rs
histogram/src/indexing/u64.rs
histogram/src/indexing/u8.rs

Applies the same improvement from #35 to AtomicHistogram
Adds benchmarking for AtomicHistogram and improves the benchmarking
for both histogram types.
Removes one comparision for each increment operation across all
indexable types.

histogram: improve performance for atomic histogram sub_assign

---

heatmap/src/heatmaps/atomic.rs
heatmap/src/heatmaps/standard.rs
heatmap/src/lib.rs
metrics/src/summary/mod.rs
waterfall/examples/simulator.rs

Changes the API of the heatmap constructor to take a 'span' of time
instead of the number of 'windows' to hold. This can allow for
easier usage particularly if resoltion is parameterized but a fixed
span of time should be represented.

heatmap: convert constructor to take a span

---

histogram/benches/atomic.rs
histogram/benches/standard.rs
histogram/src/indexing/u16.rs
histogram/src/indexing/u32.rs
histogram/src/indexing/u64.rs
histogram/src/indexing/u8.rs

There's a slowpath for sub_assign() when two histograms have
different configuration. This is probably less likely to get hit,
but the optimizations apply to iterator performance too.
Some optimizations in calculating the value for a bucket index
yields about 30% improvement on sub_assign() slow path.

histogram: improvements to sub_assign() perf for slow path

---

metrics/Cargo.toml
metrics/benches/counters.rs
metrics/src/channel/mod.rs
metrics/src/entry/mod.rs
metrics/src/metrics/mod.rs
metrics/src/outputs/mod.rs
metrics/src/summary/mod.rs
metrics/src/traits/statistic.rs

Improve metrics performance by reducing allocations and simplifying metric
lookups.
Improves record_counter() performance by ~120% (~54% latency reduction).

metrics: performance improvements

---

metrics/Cargo.toml
metrics/src/channel/mod.rs

Gets a nice speedup by replacing the RwLock with AtomicCell for the
last refreshed time of the channel.
Increases throughput by ~97% on my laptop.

metrics: use crossbeam AtomicCell instead of RwLock

---

histogram/src/histograms/atomic.rs
histogram/src/histograms/standard.rs
histogram/src/indexing/u64.rs

Improves sub_assign by addressing out-of-range values and adding
notes about function behaviors.
Adds add_assign method for histograms.
Fixes a clippy lint.

histogram: improve sub_assign and implement add_assign

---

Cargo.toml
buffer/Cargo.toml
buffer/README.md
buffer/src/lib.rs

Adds a new library which provides bi-directional buffering for
socket communications. Useful in clients and servers. Will be used
to unify the implementations in pelikan and rpc-perf.

adds a bi-directional buffer library

---

metrics/src/channel/mod.rs

Updates the metrics library to replace hashset for output tracking
with dashset. This removes a mutex.

metrics: replace hashset with dashset

---

buffer/Cargo.toml
buffer/README.md
buffer/src/lib.rs

Changes the buffer API to have better coherence with the std::io
Read, Write, and BufRead traits.
Fixes that the internal buffer types leaked as a return type.
Changes rx/tx to read/write to make it less tied to sockets.

improve buffer api

---

buffer/Cargo.toml
buffer/src/lib.rs

When used in long-running sessions, we need to address buffer bloat
from handling large requests and responses. This change adds a
private new type that wrapes BufMut providing automatic shrinking
if possible when the buffer is cleared or bytes are consumed.

buffer: enable automatic buffer shrinking

---

Cargo.toml
queue/Cargo.toml
queue/src/circleq.rs
queue/src/lib.rs
queue/src/list.rs
queue/src/slist.rs
queue/src/stailq.rs
queue/src/tailq.rs

Adding a queue library based on Rust Standard Library and ccommon
queue library. This provides singly-linked and doubly-linked lists
and tail queues as well as a circle queue.
This is an initial commit and future changes may be necessary to
accomodate usage in Pelikan.

add queue library

---

Cargo.toml
fastmetrics/Cargo.toml
fastmetrics/benches/counter.rs
fastmetrics/src/lib.rs

Adds a new metrics library 'fastmetrics' which uses a directly
indexed collection of channels. This reduces metric->channel lookup
costs at the expense of reduced flexibility and functionality
compared to 'metrics'.
This library is roughly 50x faster on my laptop.

add fastmetrics

---

heatmap/Cargo.toml
heatmap/src/heatmaps/atomic.rs
heatmap/src/heatmaps/standard.rs
heatmap/src/window/mod.rs

We directly access a slice in the heatmap using [] which can cause
a panic if the index is out of bounds.
Changes to .get()/.get_mut() to access the slice and prevent panic
if the slice index is out-of-range.

heatmap: bugfix for AtomicHeatmap

---

fastmetrics/Cargo.toml
fastmetrics/benches/counter.rs
fastmetrics/src/lib.rs
fastmetrics/src/macros.rs

Improves the fastmetrics ergonomics by removing the need to import
`metrics()` into scope.

fastmetrics: improve ergonomics

---

Cargo.toml
time/Cargo.toml
time/src/lib.rs

Initial commit of a basic time library which provides alternate
implementations of `Instant` and `Duration` including an
`AtomicInstant`.

rustcommon-time: initial commit

---

time/Cargo.toml
time/src/lib.rs

Adds coarse variants of instant and duration for cases where we do
not need high resolution times.

rustcommon-time: add coarse variants of instant and duration

---

time/Cargo.toml
time/src/lib.rs

Derive common traits for duration types.

rustcommon-time: derive common traits for duration types

---

time/Cargo.toml
time/src/lib.rs

Adds constructors and constants for duration types

rustcommon-time: add duration constructors and constants

---

atomics/src/macros/fetch_compare_store.rs
atomics/src/macros/float.rs
atomics/src/macros/float_arithmetic.rs
atomics/src/macros/float_saturating_arithmetic.rs
atomics/src/macros/native.rs
atomics/src/macros/saturating_arithmetic.rs
atomics/src/traits/atomic.rs
atomics/src/types/f32.rs
atomics/src/types/f64.rs
atomics/src/types/i16.rs
atomics/src/types/i32.rs
atomics/src/types/i64.rs
atomics/src/types/i8.rs
atomics/src/types/isize.rs
atomics/src/types/u16.rs
atomics/src/types/u32.rs
atomics/src/types/u64.rs
atomics/src/types/u8.rs
atomics/src/types/usize.rs
streamstats/src/lib.rs

Compare and swap in core is deprecated. Removes compare and swap
and migrates all internal use to compare exchange.
Simplifies fetch max and min functions to use the stabilized
functions in core.

atomics: remove compare_and_swap()

---

time/Cargo.toml
time/src/lib.rs

Problem
For frequent timestamping where we don't need the current clock reading,
we can use a cached recent value.
Solution
This is accomplished by adding an internal clock struct which contains a
cached reading of the underlying clock. We then add `Instant::recent()`
and `CoarseInstant::recent()` functions to construct new instants from
the cached view of the clock.
The cached clock must be periodically refreshed by using the public
`refresh_clock()` function.

rustcommon-time: add methods to return recent instants

---

time/Cargo.toml
time/src/duration/coarse/atomic.rs
time/src/duration/coarse/mod.rs
time/src/duration/coarse/plain.rs
time/src/duration/mod.rs
time/src/duration/precise/atomic.rs
time/src/duration/precise/mod.rs
time/src/duration/precise/plain.rs
time/src/instant/coarse/mod.rs
time/src/instant/coarse/plain.rs
time/src/instant/mod.rs
time/src/instant/precise/atomic.rs
time/src/instant/precise/mod.rs
time/src/instant/precise/plain.rs
time/src/lib.rs

Normalize the interface for the duration types by copy-pasting from
rust std/core implementations.
This helps provide a consistent and familiar interface, improves the
documentation, and makes sure we have a more complete api.

time: normalize interfaces with core/std

---

queue/src/circleq.rs

Originally `pop_back_node` would set the head's `prev` pointer to `self.head` instead of `self.tail`, which is a logic error to start with. This error can also cause `split_off` to create two lists with the same node (which is UB), if used (in)correctly.
Simply changed `pop_back_node` to correctly set the head's `prev` to `self.tail`.
The CircleQ seems a bit broken in general, aside from just this. Whether or not the `self.head`'s `prev` will point to `self.tail` isn't consistent. Some methods tie this up, some do not.

Fixed CircleQ pop_back_node pointer issues

---

time/Cargo.toml
time/benches/precise.rs

Adds basic criterion benchmarks for the precise Instant type, both
plain and atomic, to evaluate performance of any changes to the
crate.

rustcommon_time: add basic criterion benchmarks

---

fastmetrics/src/metrics.rs

Migrate from deprecated `spin_loop_hint()` to `hint::spin_loop()`

fastmetrics: update spin loop hint

---

Cargo.toml
metrics-v2/Cargo.toml
metrics-v2/src/counter.rs
metrics-v2/src/gauge.rs
metrics-v2/src/lib.rs
metrics-v2/src/macros.rs

We were interested in bringing in the `metrics` crate from https://github.com/phantomical/hamerkop/metrics (which is my other gh account). 
This PR ports over the parts of that crate that I'm happy with design-wise. Namely:
- the mechanism for registering static metrics and putting them in a single distributed slice, and,
- types for counter and gauge metrics.
The rest will be brought over or redesigned in follow-up PRs.
For now, I'm putting the new metrics implementation under a `metrics-v2` folder (name up to bikeshedding) although I think the goal should be to remove the existing `rustcommon-metrics` crate - which I think has no consumers - with this one once it is feature-complete.

Bring in new metrics implementation

---

time/Cargo.toml
time/src/lib.rs

Adds support to return SystemTime and DateTime types
Changes `now` methods to refresh the clock.

time: add SystemTime and DateTime support

---

time/src/lib.rs

Change the re-export to include all of chrono::prelude to allow
for more convenient operations with `DateTime<>` types.

time: re-export chrono::prelude

---

.github/workflows/cargo.yml
.github/workflows/ci.sh

CI is slow. There are many things that could be cached and code is checked and then rebuilt.
This PR replaces the existing workflow in `.github/workflows/cargo.yml` with a new updated one.
Here's a summary of the changes I've made:
- Use the actions from https://github.com/actions-rs to set up the toolchain and run cargo commands
- Consolidate common workflows on different platforms using a build matrix
- Add builds for both release and debug modes
- Cache downloaded crates and build outputs using https://github.com/Swatinem/rust-cache
- Optimize the doc tests for `rustcommon-time` as they were very slow when running in release mode
Previously the build step took ~9-10 minutes to run in CI. When cached it now takes ~4m 30s for the release builds and ~1m for the debug builds.
There are …

Improve performance of CI

---

metrics-v2/Cargo.toml
metrics-v2/derive/src/metric.rs
metrics-v2/src/dynmetrics.rs
metrics-v2/src/lib.rs
metrics-v2/tests/dynmetrics.rs
metrics-v2/tests/named_metric.rs
metrics-v2/tests/unnamed_metric.rs

Currently, the only way to register metrics in metrics-v2 is to create a static and use the `#[metric]` attribute on it. This doesn't work if the metric needs to be created dynamically or shouldn't be around for the entire lifetime of the program.
This PR adds a global registry of dynamic metrics along with some wrapping types that make working with dynamic metrics easier. It also extends the `metrics` function to return both static and dynamic metrics.
To create and use dynamic metrics you'll have to use one of `DynPinnedMetric` or `DynBoxedMetric`. These have different tradeoffs: `DynPinnedMetric` stores the metric inline but must be pinned in order to be registered, `DynBoxedMetric` stores the metric on the heap so it can be used as a regular rust type. Otherwise these types can be …

metrics-v2: Implement dynamic metrics

---

metrics-v2/derive/src/args.rs
metrics-v2/derive/src/lib.rs
metrics-v2/derive/src/metric.rs
metrics-v2/tests/alternate_crate.rs

I've been converting the metrics in pelikan to use metrics-v2. This has involved using metrics-v2 from within a custom macro. However, the `#[metrics]` attribute macro needs to be able to find the `rustcommon_metrics_v2` crate in order to work, this is not possible when it is used by a macro in a crate that doesn't list `rustcommon_metrics_v2` in it's dependencies.
This PR adds a `crate` argument to the `#[metrics]` attribute macro that overrides the default path to `rustcommon_metrics_v2` in the generated code. That is enough for it to be usable when reexported from a macro.

metrics-v2: Add `crate` macro parameter to specify custom metrics crate location

---

metrics-v2/derive/src/metric.rs
metrics-v2/src/lib.rs

Previously we were searching for `rustcommon_metrics_v2` but the crate is actually named `rustcommon-metrics-v2`.
This wasn't noticed earlier because the fallback was to just use the exact crate name which worked most of the time. In all other cases, the crate search path was explicitly overridden.

metrics-v2: Actually search for the correct crate name

---

.github/workflows/cargo.yml

The doctests in CI are the slowest part since they need to link a binary for each one. In debug mode this isn't so bad but it is extremely slow in release mode.
We only run the doctests in debug mode.

Adjust CI to run all doctests in a separate step and only in debug mode

---

metrics-v2/Cargo.toml
metrics-v2/src/heatmap.rs
metrics-v2/src/histogram.rs
metrics-v2/src/lazy.rs
metrics-v2/src/lib.rs

We'd like to be able to use heatmaps as metrics for a couple of downstream crates.
This PR adds support for using the `AtomicHeatmap` from `rustcommon-heatmap` as a metric. This is gated behind the `heatmap` feature of the metrics crate in case it isn't always wanted.
Since the heatmap constructor functions are not `const` I also needed to implement a lazy cell that would allow for it to be initialized at runtime. Unfortunately `once_cell::sync::Lazy` didn't have the APIs I needed and `std::lazy::Lazy` is not stable yet. As an alternative, I've written my own that is closely based on the implementation of `once_cell::sync::Lazy` and implemented `Metric` for that.

metrics-v2: Allow using heatmaps as metrics

---

metrics-v2/src/gauge.rs

Counter already does this so this brings Gauge up to parity. I've ended up needing this within rezolus.

[metrics-v2] Make gauge return the previous value on modification

---

metrics-v2/src/dynmetrics.rs

We want to be able to create `DynBoxedMetric`s and dynamically decide whether or not to enable them at a later point. This currently is not something that can be done.
Add the requisite APIs to do so.

[metrics-v2] Allow creating unregistered `DynBoxedMetric`s

---

metrics-v2/src/lazy.rs
metrics-v2/src/lib.rs

In pelikan we've wanted to have metrics that need a `Lazy` but at the same time we want them to be initialized even if the client code has not used them.
This PR introduces a wrapper around `Lazy` called `Relaxed` (name open to bikeshedding) which will also get initialized when accessed via the global metrics array. It can be used anywhere `Lazy` can and will always appear to be initialized when looking at all the metrics.

[metrics-v2] Add non-fully-lazy variant of Lazy cell

---

.github/workflows/cargo.yml
heatmap/benches/heatmaps.rs
metrics/benches/counters.rs

Benchmarks weren't updated as part of #96 and #97. This change
fixes the benchmarks to use the time types in rustcommon-time

fix benchmarks

---

time/Cargo.toml
time/benches/precise.rs
time/examples/demo.rs
time/src/lib.rs

Increases the precision of UTC timestamps to include sub-second
component.
Adds new unix precise functions to return the unix time with
nanosecond resolution.

time: increase precision for UTC and unix times

---

time/Cargo.toml
time/examples/demo.rs
time/src/lib.rs

Bugfix for incorrect initialization introduced by #99
Improves correctness for race conditions during initialization or
refresh.

time: bugfix for initialization

---

time/src/instant/coarse/atomic.rs
time/src/instant/coarse/mod.rs
time/src/lib.rs

Refactor time::instant::coarse to move atomic type into its own
module. This makes it consistent with the other modules.

time: refactoring

---

metrics/src/lib.rs
time/src/unix.rs

When working with raw unix times, it would be helpful to convert
them into `UnixInstant` types so we can perform normal instant
math.
Adds constructors to create coarse and precise `UnixInstant`s from
raw values.

time: allow constructing unix instants for specific times

---

.github/workflows/cargo.yml
metrics-v2/Cargo.toml

Updates linkme to a new version which contains a fix to allow us
to use current stable Rust.

metrics: update linkme and use stable rust for testing

---

streamstats/src/lib.rs
time/src/duration.rs
time/src/lib.rs

Add consts for common durations like those in core::time::Duration.

time: add consts for common durations

---

time/src/macros.rs

The Rust standard library changed the behavior of duration_since()
to be a saturating operation.
This change makes sure out library behaves the same way.

time: change duration_since() to match std library

---

metrics/derive/src/metric.rs
metrics/src/lib.rs
metrics/tests/namespaced_metric.rs

By adding an optional namespace for each metric, we can easily change the displayed metric name by including some prefix. For example, we may want to prefix client metrics with `client` but only if we're also displaying `server` metrics (for example, in a proxy). This can be achieved by combining feature flags and custom macros.

metric namespace

---

metrics/src/lib.rs
metrics/tests/heatmap.rs

Heatmap macro was broken by #122
Fixes the heatmap initialization and adds a test to prevent a miss here in the future.

metrics: fix heatmap macro

---

metrics/derive/src/lib.rs
metrics/src/lazy.rs
metrics/src/lib.rs
metrics/tests/heatmap.rs
metrics/tests/metric_macros.rs

This PR fixes two main problems:
- the metrics crate re-exports the entirety of the `rustcommon_time` crate
- all the new macros in the metrics crate have `rustcommon_metrics` hardcoded as the crate name which will break if the crate is ever renamed or used in a edition 2015/2018 crate with a module called `rustcommon_metrics`
Here's what I've changed:
- the relevant re-exports from time have been added to the hidden `exports` module (that's what it is there for)
- I have also marked the `to_lowercase!` macro as `#[doc(hidden)]` since it's not relevant to the public api of the crate
- I have gone through and replaced any instance of `rustcommon_metrics` in the exported macros with `$crate` so that it will refer to the right crate
- I have also added `crate = $crate` to the invocations of …

fix(metrics): Remove public re-exports of rustcommon-time from metrics
